### ISSUE TITLE
APsystems-EZ1 hangs when trying to implement zero feed-in

### ISSUE THREAD

**Issue by pitticom** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#28]
Hello
I'm trying to achieve zero feed-in with the APsystems-EZ1.
https://github.com/AndreBott83/HA_Zero_PV_Grid_Feed_in
It works well at first, but the inverter freezes after a few minutes. Unfortunately it is no longer accessible via the network.
I then have to connect via Bluetooth and activate and deactivate direct mode a few times until the APsystems-EZ1 gets an IP address again.
The query interval has been extended to 30 seconds, but there is no change.
Can anyone understand that?

**Comment by dekoenpi** [comment]
After how many minutes does it freeze?
In my case, I have a Shelly Pro 3EM. This measures in both directions. No inverter freeze (newest firmware).

![image](https://github.com/SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant/assets/72542132/05adb09f-3fba-4f85-bad3-a3af0172a96a)

![image](https://github.com/SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant/assets/72542132/749a1afd-27e1-48dc-90a3-73304ade3eaf)

Nulleinspeisung = zero-feed-in
Wechselrichter = Inverter
BKW = Balcony power station

```
alias: Nulleinspeisung
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.shelly_pro_3em_total_active_power
    alias: Verbrauch ändert sich
condition:
  - alias: Solar Prod > Verbrauch
    condition: template
    value_template: >-
      {{ states('sensor.bkw_total_power') | float >
      states('sensor.shelly_pro_3em_total_active_power') | float }}
action:
  - service: number.set_value
    metadata: {}
    data:
      value: >-
        {{ states('sensor.shelly_pro_3em_total_active_power') | float +
        states('sensor.bkw_total_power') | float }}
    target:
      entity_id: number.apsystems_bkw_max_output_power
    alias: Wechselrichter anpassen
mode: single
```
